### ISSUE TITLE
Issue with Angular 10

### ISSUE THREAD

**Issue by nitinht1988** [sliceofbytes/ngx-videogular#11]
Hi @sliceofbytes 

After upgrading to Angular 10, I am getting the following errors.

`ERROR in node_modules/ngx-videogular/lib/core/vg-media/i-media-element.d.ts:17:27 - error TS2304: Cannot find name 'AudioTrackList'.

17     readonly audioTracks: AudioTrackList;
                             ~~~~~~~~~~~~~~
node_modules/ngx-videogular/lib/core/vg-media/i-media-element.d.ts:139:27 - error TS2304: Cannot find name 'VideoTrackList'.

139     readonly videoTracks: VideoTrackList;
                              ~~~~~~~~~~~~~~
node_modules/ngx-videogular/lib/core/vg-media/vg-media-element.d.ts:5:24 - error TS2304: Cannot find name 'AudioTrackList'.

5     get audioTracks(): AudioTrackList;
                         ~~~~~~~~~~~~~~
node_modules/ngx-videogular/lib/core/vg-media/vg-media-element.d.ts:42:18 - error TS2304: Cannot find name 'VideoTrackList'.

42     videoTracks: VideoTrackList;
                    ~~~~~~~~~~~~~~`

Thank you in advance.

**Comment by sliceofbytes** [comment]
I've pushed a new version for angular 10 with the interfaces needed. Sorry for the slow update.
