### ISSUE TITLE
Can we have specific start time and in videoangular2 video player? i.e if I want my video to start from1min, Is it possible?

### ISSUE THREAD

**Issue by anushreenk** [sliceofbytes/ngx-videogular#12]

**Comment by sliceofbytes** [comment]
Yes, to start a video from a specific area you can use a couple different strategies. If your video source supports fragments you can just use a url fragment myVideo.webm#t=60

If that doesn't work for you, you can wait until the video duration is known by the browser and set currentTime before it's able to be played.

Hook loadedMetadata or loadedData events and set currentTime = 60.
