### ISSUE TITLE
Update to Angular 

### ISSUE THREAD

**Issue by allancmello** [sliceofbytes/ngx-videogular#33]
Hi,

Do you have any plans to update ngx-videogular to Angular version 13?

**Comment by sliceofbytes** [comment]
Yes I can release a version updated for 13.

**Comment by redster51** [comment]
That would be great! How much time does it take? :)

**Comment by sliceofbytes** [comment]
> That would be great! How much time does it take? :)

I've pushed an updated version to npm. It should be available now 13.2.2-0.

**Comment by sliceofbytes** [comment]
Just a follow up to this, I won't be able to push a new version until Friday. I need to fix one more dependency (changing rxjs to ^7.4.0 for the root project and the library to eliminate the install error.  It will work fine if you force install it but that is obviously not ideal.
