### ISSUE TITLE
Videogular2 is not playing video only in android devices

### ISSUE THREAD

**Issue by mbabaei0** [sliceofbytes/ngx-videogular#4]
Currently, I'm using videogular2 (ngx-videogular) in my angular9 project. everything works fine in Desktop browsers and Even on iPhone devices. but when I open my website in the Android Chrome browser video is not playing and just loading spinner shows for me.

I tired ng serve --host 0.0.0.0 and opened my localhost in an android device but this time it works fine for me.

**Comment by sliceofbytes** [comment]
> Currently, I'm using videogular2 (ngx-videogular) in my angular9 project. everything works fine in Desktop browsers and Even on iPhone devices. but when I open my website in the Android Chrome browser video is not playing and just loading spinner shows for me.
> 
> I tired ng serve --host 0.0.0.0 and opened my localhost in an android device but this time it works fine for me.

Can you give me some more info on the device and any errors you might have encountered. In general this is working for android devices, so it might be a device/browser/configuration issue.
