### ISSUE TITLE
Cannot find name "AudioTrackList"...

### ISSUE THREAD

**Issue by rostalevicek** [sliceofbytes/ngx-videogular#5]
Hi, I have smae problem like with videogular2 when compiling with Angular 9. Internal references can not be resolved. Can you help please?
Thanks!

**Comment by UserNobody14** [comment]
I'm getting the same error with angular 10:

![image](https://user-images.githubusercontent.com/38988442/87233380-b13a4080-c37b-11ea-855e-f50b8fa70c55.png)

**Comment by St1c** [comment]
same error here

**Comment by masonzhang** [comment]
same error here with angular 10

**Comment by sliceofbytes** [comment]
I've pushed an update for angular 10 , I apologize for the slow update been a crazy few months.
